###################################################
#  _    __      _     __________              __  #
# | |  / /___  (_)___/ / ____/ /_  ___  _____/ /_ #
# | | / / __ \/ / __  / /   / __ \/ _ \/ ___/ __/ #
# | |/ / /_/ / / /_/ / /___/ / / /  __(__  ) /_   #
# |___/\____/_/\__,_/\____/_/ /_/\___/____/\__/   #
#                                                 #
#                v1.0 by Biscut                   #
###################################################

# How often voidchests should sell their contents, in seconds.
sell-time: 1.0

# How often voidchest locations should save to config, in seconds (good for when crashes happen).
save-time: 300.0

# Set to false if you don't want unsellable items to be cleared.
# ex. if this is true and bedrock is found in a voidchest with a value of $0,
# it will still be removed from the chest.
remove-unsellable-items: true

# Options: PLAYER, FACTION_LEADER, FACTION_BALANCE, ISLAND_OWNER, PLOT_OWNER;
money-recipient: 'PLAYER'

# Shift and punch the voidchest to easily break & return a voidchest (recommended)
sneak-punch-to-break: true

# Drop the voidchest on the floor if the player's inventory is full when doing /vc give
command-drop-if-full: true

# Whether to put the voidchest directly in the player's inventory when breaking it
break-give-to-inventory: true

# Drop the voidchest on the floor if the player's inventory is full when breaking the voidchest (applies if above is true)
break-drop-if-full: true

# If set to false, only the respective owners/team members can break this chest.
# For example, if money-recipient: is set to FACTION_LEADER or FACTION_BALANCE, anyone
# in the faction can break the chest.
anyone-can-break: false

# The minimum factions rank that can break voidchests, only works if factions hook is enabled.
minimum-factions-rank-break: 'MEMBER'

# Customize the voidchest item.
item:
  material: 'CHEST' # Note, the physical block will always be a chest regardless of this material.
  name: '&6&lVoidChest'
  lore:
    - '&7Anything placed in this chest will be automatically sold'
    - '&7according to the shop price and straight into your balance.'
  glow: false

hooks:
  essentials: true # Use the worth.yml from Essentials for prices
  shopguiplus: false # Use prices from ShopGUI+ (unfortunately, I can only get prices while the player, faction leader, or island owner is online
  # unless if shopguiplus-workaround is enabled- where it will then get the prices from any other random online player).
  askyblock: false
  factions: true
  plotsquared: false

# Allow the plugin to fetch ShopGUI+ prices while the money recipient is offline.
# This workaround will instead take the prices from any random online player. Would only recommend
# using this if the shop prices are the same for all players in your server.
shopguiplus-workaround: false

# Customize messages from the plugin.
messages:
  voidchest-beside-chest: '&cYou cannot place a voidchest beside another chest!'
  chest-beside-voidchest: '&cYou cannot place a chest beside a voidchest!'
  voidchest-removed: '&aVoidchest removed and added to your inventory!'
  voidchest-remove-nospace: '&cYou must have an empty inventory slot to break this voidchest!'
  voidchest-remove-notowner: '&cYou cannot destroy a voidchest that is not yours!'
  voidchest-place: '&aVoidchest placed!'
  voidchest-receive: '&aYou have received {amount} voidchests!'
  no-permission-place: '&cYou do not have permission to place a voidchest!'
  no-permission-command: '&cNo permission!'
  not-minimum-faction: '&cYou are not the minimum factions role!'

# These prices will be used as a last resort if none of the hooks above are enabled.
prices:
  dirt: 1.0
  bedrock: 2.0
  iron_ingot: 0.5

# Set to false if you don't want your ops to get update messages. (Recommended: true)
update-messages: true

# Please do not change this!
config-version: 1.0
