name: VoidChest
version: 1.0
api-version: 1.13
main: codes.biscuit.voidchest.VoidChest
author: Biscut
description: Automatically sells all items that enter a voidchest.
depend: [Vault]
softdepend: [ShopGUIPlus, PlotSquared, Factions, MassiveCore, Essentials, ASkyBlock]
commands:
  voidchest:
    description: The main voidchest command.
    aliases: [vc]
permissions:
  voidchest.admin:
    description: Access to the main voidchest command.
    default: op
  voidchest.place:
    description: Ability to place voidchests.
    default: true