name: SellChest
version: ${version}
api-version: 1.13
main: codes.biscuit.sellchest.SellChest
author: Biscut
description: Automatically sells all items that enter a sellchest.
depend: [Vault]
softdepend: [ShopGUIPlus, PlotSquared, Factions, MassiveCore, Essentials, ASkyBlock]
commands:
  sellchest:
    description: The main sellchest command.
    aliases: [sc]
permissions:
  sellchest.admin:
    description: Access to the main sellchest command.
    default: op
  sellchest.place:
    description: Ability to place sellchests.
    default: true